default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "<your_password>") %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL__DATABASE_APP", "mdoner-chatbot") %>

# test:
#   <<: *default
#   database: mdoner-chatbot-test

production:
  url: <%= ENV['DATABASE_URL'] %>