default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "freee") %>

development:
  <<: *default
  database: dpr_chatbot_development

test:
  <<: *default
  database: dpr_chatbot_test

production:
  url: <%= ENV['DATABASE_URL'] %>
